/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/alerts`; params?: Router.UnknownInputParams; } | { pathname: `/caretakers`; params?: Router.UnknownInputParams; } | { pathname: `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/emergencyContacts`; params?: Router.UnknownInputParams; } | { pathname: `/forgot-password`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/profile-setup`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/reports`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/../utils/twilioTester`; params?: Router.UnknownInputParams; } | { pathname: `/debug/twilio-test`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/vitals/blood-pressure`; params?: Router.UnknownInputParams; } | { pathname: `/vitals/ecg-details`; params?: Router.UnknownInputParams; } | { pathname: `/vitals/ecg`; params?: Router.UnknownInputParams; } | { pathname: `/vitals/heart-rate`; params?: Router.UnknownInputParams; } | { pathname: `/vitals/oxygen`; params?: Router.UnknownInputParams; } | { pathname: `/vitals/temperature`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/alerts`; params?: Router.UnknownOutputParams; } | { pathname: `/caretakers`; params?: Router.UnknownOutputParams; } | { pathname: `/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/emergencyContacts`; params?: Router.UnknownOutputParams; } | { pathname: `/forgot-password`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/profile-setup`; params?: Router.UnknownOutputParams; } | { pathname: `/register`; params?: Router.UnknownOutputParams; } | { pathname: `/reports`; params?: Router.UnknownOutputParams; } | { pathname: `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/../utils/twilioTester`; params?: Router.UnknownOutputParams; } | { pathname: `/debug/twilio-test`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/vitals/blood-pressure`; params?: Router.UnknownOutputParams; } | { pathname: `/vitals/ecg-details`; params?: Router.UnknownOutputParams; } | { pathname: `/vitals/ecg`; params?: Router.UnknownOutputParams; } | { pathname: `/vitals/heart-rate`; params?: Router.UnknownOutputParams; } | { pathname: `/vitals/oxygen`; params?: Router.UnknownOutputParams; } | { pathname: `/vitals/temperature`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/alerts${`?${string}` | `#${string}` | ''}` | `/caretakers${`?${string}` | `#${string}` | ''}` | `/dashboard${`?${string}` | `#${string}` | ''}` | `/emergencyContacts${`?${string}` | `#${string}` | ''}` | `/forgot-password${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/profile-setup${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `/reports${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/../utils/twilioTester${`?${string}` | `#${string}` | ''}` | `/debug/twilio-test${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/vitals/blood-pressure${`?${string}` | `#${string}` | ''}` | `/vitals/ecg-details${`?${string}` | `#${string}` | ''}` | `/vitals/ecg${`?${string}` | `#${string}` | ''}` | `/vitals/heart-rate${`?${string}` | `#${string}` | ''}` | `/vitals/oxygen${`?${string}` | `#${string}` | ''}` | `/vitals/temperature${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/alerts`; params?: Router.UnknownInputParams; } | { pathname: `/caretakers`; params?: Router.UnknownInputParams; } | { pathname: `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/emergencyContacts`; params?: Router.UnknownInputParams; } | { pathname: `/forgot-password`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/profile-setup`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/reports`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/../utils/twilioTester`; params?: Router.UnknownInputParams; } | { pathname: `/debug/twilio-test`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/vitals/blood-pressure`; params?: Router.UnknownInputParams; } | { pathname: `/vitals/ecg-details`; params?: Router.UnknownInputParams; } | { pathname: `/vitals/ecg`; params?: Router.UnknownInputParams; } | { pathname: `/vitals/heart-rate`; params?: Router.UnknownInputParams; } | { pathname: `/vitals/oxygen`; params?: Router.UnknownInputParams; } | { pathname: `/vitals/temperature`; params?: Router.UnknownInputParams; };
    }
  }
}
